
package com.travelAgency.ws.hotel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelServiceImpl", targetNamespace = "http://ws.travelAgency.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.travelAgency.ws.hotel.Hotel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHotel", targetNamespace = "http://ws.travelAgency.com/", className = "com.travelAgency.ws.hotel.GetHotel")
    @ResponseWrapper(localName = "getHotelResponse", targetNamespace = "http://ws.travelAgency.com/", className = "com.travelAgency.ws.hotel.GetHotelResponse")
    @Action(input = "http://ws.travelAgency.com/HotelServiceImpl/getHotelRequest", output = "http://ws.travelAgency.com/HotelServiceImpl/getHotelResponse")
    public Hotel getHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addHotel", targetNamespace = "http://ws.travelAgency.com/", className = "com.travelAgency.ws.hotel.AddHotel")
    @ResponseWrapper(localName = "addHotelResponse", targetNamespace = "http://ws.travelAgency.com/", className = "com.travelAgency.ws.hotel.AddHotelResponse")
    @Action(input = "http://ws.travelAgency.com/HotelServiceImpl/addHotelRequest", output = "http://ws.travelAgency.com/HotelServiceImpl/addHotelResponse")
    public boolean addHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Hotel arg0);

}
